### ISSUE TITLE
Use only milliseconds for `begin`, `end`, and derived columns 

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/scikit-talk#12]
Timestamps are a PITA across datasets and platforms and require careful conversions and tests. In ElPaCo we've made an early choice to convert all timestamps in incoming data to milliseconds counted from the beginning of the source recording. Reasons:

- milliseconds offer the right level of precision (seconds don't: people are sensitive to timing differences on the order of 0.1s)
- this makes them also useful as a key part of the UID, the utterance-level unique identifier we use throughout
- milliseconds are simple integers that are easy to manipulate for all sorts of time-related measures (`duration`, length of overlap, etc.)
- milliseconds are the 'industry standard' for work on the timing of turn-taking (FTO)

My proposal is to make sure there is a simple and robust function to handle the timestamp to millisecond conversion at the earliest moment of import, and perhaps some tests to check that timestamp data at later stages are milliseconds. And that all subsequent levels of data processing and data dumping in both `scikit-talk` and `talkr` deal with timing data only in milliseconds. This will continue to save us a lot of headaches.

**Comment by liesenf** [comment]
Agree. That function is in 'dataloader.py'.
