### ISSUE TITLE
add eaf parser

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/scikit-talk#36]

**Comment by carschno** [comment]
I suppose [this](https://www.mpi.nl/tools/elan/EAF_Annotation_Format_3.0_and_ELAN.pdf) is the specification of EAF.

**Comment by carschno** [comment]
EAF parser: https://speach.readthedocs.io/en/latest/index.html

**Comment by mdingemanse** [comment]
The main trouble with eaf is that you don't know beforehand which tiers are going to contain the `utterance` content that we actually want to parse.

This means you'll need to have some kind of UI where either 

1. you let the user give a list of desired tiers (this presupposes the user has that list beforehand)
2. you present the user with some sample content, allowing them to choose the desired tiers 

After that, you would probably also need some checks that will enable the user to see whether they made the right choice, and redo as needed.

**Comment by mdingemanse** [comment]
todo for @liesenf: pick 2 openly available eaf corpora that we have parsed before, enumerate the desired tiers & show the parsing code

**Comment by bvreede** [comment]
One would be [IFADV](https://www.fon.hum.uva.nl/IFA-SpokenLanguageCorpora/IFADVcorpus/Annotations/EAF/)

**Comment by bvreede** [comment]
> The main trouble with eaf is that you don't know beforehand which tiers are going to contain the `utterance` content that we actually want to parse.
> 
> This means you'll need to have some kind of UI where either
> 
> 1. you let the user give a list of desired tiers (this presupposes the user has that list beforehand)
> 2. you present the user with some sample content, allowing them to choose the desired tiers
> 
> After that, you would probably also need some checks that will enable the user to see whether they made the right choice, and redo as needed.

@mdingemanse check the [documentation](https://sktalk.readthedocs.io/en/latest/notebooks/example.html#Parsing-an-.eaf-file)! Any feedback/corrections, feel free to re-open this issue.

**Comment by mdingemanse** [comment]
docs are looking good!
