### ISSUE TITLE
Build JSON corpus object

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/scikit-talk#6]
Using convokit module, see https://github.com/CornellNLP/ConvoKit/blob/master/convokit/model/corpus.py

**Comment by liesenf** [comment]
This folder contains documents to plan building the `build_corpus` function that transforms `csv` files into `json` objects.

### Content: 

- Example input: several corpora as `.csv` files
- Example output: the switchboard corpus in `.json` and `.jsonl` format
- A script that uses `convokit` to build json objects that we can edit and adapt
- A notebook to build the `build_corpus` function in



We can build on and edit the corpus structure that `convokit` is using:

https://convokit.cornell.edu/documentation/data_format.html

The mandatory data fields of `utterances.jsonl` need to be edited as follows:

| `convokit`                                                                                                 | `scitkit-talk`                                        |
|------------------------------------------------------------------------------------------------------------|-------------------------------------------------------|
| id: index of the utterance                                                                                 | rename to `uid`                                       |
| speaker: the speaker who authored the utterance                                                            | rename to `participant`                               |
| conversation_id: id of the first utterance in the conversation this utterance belongs to                   | stays the same                                        |
| reply_to: index of the utterance to which this utterance replies to (None if the utterance is not a reply) | can be deleted                                        |
| timestamp: time of the utterance                                                                           | needs to be split into `begin` and `end`              |
| text: textual content of the utterance                                                                     | rename to `utterance`                                 |
|                                                                                                            | add `source` field that contains `path` to audio file |

`speaker.json` `conversation.json` `corpus.json` `index.json` contain optional metadata and can stay the same.

**Comment by liesenf** [comment]
Notes to plan the `build_corpus() ` function

Input:

A `.csv` files with (at least) the following columns:

`begin`

`end`

`participant`

`utterance`

`source`

Output:

A folder with several `.json `and` .jsonl `objects:

`conversations.json`

`corpus.json`

`index.json`

`speakers.json`

`utterances.jsonl`

**Comment by liesenf** [comment]
Editing `corpusbuilder.py`:

Im trying to get everything we need into one file, pulling together various helper functions from other places of convokit. Also commented out all functions that we don't need for now 
-

**Comment by mdingemanse** [comment]
> `speakers.json`

Can we make this `participants.json` for consistency and modality-inclusivity? ;)
