### ISSUE TITLE
compute FTO only for dyadic or triadic stretches

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/scikit-talk#8]
FTO (floor transfer offset) measures the time of a turn `begin` relative to the `end` of the most likely relevant prior turn

The code for this (which originated in R) is already pretty intricate (designed with psycholinguistic and conversation analytic facts in mind) but for broader use, it would be best to be maximally conservative: only compute FTO for stretches where two or at most three participants are in an exchange.

The reason is that from 4 participants, conversations often split (the technical term is schism) into two 1:1 conversations, in which case simplistic FTO values are useless if not downright misleading.

Since participation can vary over the course of a recording, this should be done locally, on the basis of looking back in a moving window.

Proposal: a turn by participant A can only get an FTO if in the past ten seconds there were turns by no more than two other participants B, C.

May require a first pass through all data to generate a column `participation` with values {monologue, dyadic, triadic, uncertain}.

Everything beyond triadic is uncertain because we cannot determine without analysis whether it is truly multi-party, dyadic + dyadic, dyadic + triadic, etc.

**Comment by mdingemanse** [comment]
For reference, here is the original R code for computing FTO:

```
# FTO tries takes into account the most relevant prior turn by other, which is
# not necessarily the prior row in the df. By default we only get 0, 1 and 5
# right. Cases 2 and 3 are covered by a rule that looks at turns coming in early
# for which prior turn is by self but T-2 is by other. Some cases of 4 (but not
# all) is covered by looking for turns that do not come in early but have a
# prior turn in overlap and look for the turn at T-2 by a different participant.

# A turn doesn't receive an FTO if it follows a row in the db that doesn't have
# timing information, or if it is such a row.

# A [------------------]      [0--]
# B      [1-]  [2--] [3--] [4--]    [5--]
 

d <- d %>%
  mutate(FTO = case_when(
    priorby == "other" & begin-lag(begin) < 200 & lag(priorby) != "other" ~ begin - lag(end,2),
    priorby == "other" & begin-lag(begin) < 200 & lag(priorby) != "self" & lag(priorby,2) == "other" ~ begin - lag(end,3),
    priorby == "self_during_other" & lag(participant,n=2) != participant  ~ begin - lag(end,2),
    priorby == "self_during_other" & lag(priorby) == "self_during_other" ~ begin - lag(end,3),
    priorby == "other" ~ begin - lag(end), # case 0,1,5
    priorby == "self" ~ as.double(NA),
    TRUE ~ as.double(NA)
  )) 


# note that we considered setting FTO to NA for [laugh] and [breath] (as these
# behaviours are less turn-organized), but we've chosen to maintain them so that
# we can *check* and *show* this, and can still filter them out when not
# relevant

# we do set FTO to NA if it is higher than 10s or lower than -10s, on the
# grounds that (a) psycholinguistically it is implausible that these actually
# relate to the end of the 'prior', and (b) conversation analytically it is
# necessary to treat such cases on their own terms rather than take an FTO at
# face value 

d %>% filter(FTO > 9999) %>% ungroup() %>% summarise(n=n())
d <- d %>%
  mutate(FTO = ifelse(FTO > 9999, NA,FTO))

# likewise, we set FTO to NA if it is negative < -9999, on the grounds that (a)
# psycholinguistically it is impossible to relate to the end of the 'prior'
# turn, and (b) conversation analytically it is necessary to treat such cases on
# their own terms rather than take an FTO at face value 
d %>% filter(FTO < -9999) %>% ungroup() %>% summarise(n=n())
d <- d %>%
  mutate(FTO = ifelse(FTO < -9999, NA,FTO))
```

**Comment by mdingemanse** [comment]
@liesenf, when you have some time, can you take a critical look at my reasoning in this old issue? yesterday we discussed doing FTO only for dyads but my thinking here apparently was that it may be okay for triads too. Only for 4 people and upwards can you get schisms.

But even triads are tricky. I'm thinking of situations like the one below (from [10.1515/opli-2015-0001](https://doi.org/10.1515/opli-2015-0001)), where Kuma's line 5 is responded to by both Atta and Ruben at lines 6 and 7. We can't say that the FTO of line 7 should be computed relative to line 6; it is too fast for that and is more relevantly addressed to line 5. Since a script will never be able to make such decisions, we should not autocompute FTOs in such cases.

![image](https://github.com/elpaco-escience/scikit-talk/assets/9883915/894c20c9-18ee-4118-9202-0b0b2ca0ec2f)

So, my hunch is to take the most conservative approach possible and only deliver FTOs for unproblematically dyadic stretches.

**Comment by bvreede** [comment]
In #1 I've tried to implement the calculation of FTO, but I think I'm still missing some of the details that I see here in the example code:

```
d <- d %>%
  mutate(FTO = case_when(
    priorby == "other" & begin-lag(begin) < 200 & lag(priorby) != "other" ~ begin - lag(end,2),
    priorby == "other" & begin-lag(begin) < 200 & lag(priorby) != "self" & lag(priorby,2) == "other" ~ begin - lag(end,3),
    priorby == "self_during_other" & lag(participant,n=2) != participant  ~ begin - lag(end,2),
    priorby == "self_during_other" & lag(priorby) == "self_during_other" ~ begin - lag(end,3),
    priorby == "other" ~ begin - lag(end), # case 0,1,5
    priorby == "self" ~ as.double(NA),
    TRUE ~ as.double(NA)
  )) 
```
- ~What is the nature of the function `lag()`? I see it is applied to a category (`priorby`) but also to numeric data (`begin` and `end, 2`), as well as `participant`..., I can't figure it out completely. Do you have the code for this function?~ Aha, this is R, not a function you wrote 😅 apologies. [This one, right?](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lag)
- The first condition, `priorby`, is one we don't use at all in our calculation. Here it seems crucial. Should we add it? Or is the fact that we use a timed context window sufficient?

In #1 I put some scenarios, but let me add them here; it would be good to have clarity on them. What follows is copy-pasted from the discussion in #1.

I have now incorporated the FTO calculation as we discussed, but I am noticing some issues, so I would like to double check some explicit scenarios.

In all the following scenarios, A is followed by B, is followed by C, and B and C are by a different speaker than A. The goal is to find the relevant preceding utterance for B and C, if any exist. A is in the context window for both B and C in all three scenarios; that is: the end of A is less than 10 seconds prior to the beginning of C.

Thus, in all three scenarios A meets the criteria for FTO calculation for B and C:
- within a 10 second context window
- beginning 200ms or more prior to the utterance
- by a different speaker, and the most recent utterance by this speaker
- in a dyadic context

**Scenario 1**: this seems to make sense. While there is a brief utterance (B) in the same time as A, it is clear that A is the relevant turn to calculate the FTO for C. It also makes sense to use A to calculate the FTO for B. (Right?)
<img width="435" alt="Screenshot 2023-11-21 at 22 05 25" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/a3013a46-4623-4a02-9d58-6bcac51b517c">

**Scenario 2**: this makes me wonder. Is C really a response to A, or rather a continuation of B?
<img width="518" alt="Screenshot 2023-11-21 at 22 06 09" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/01c1dce8-725c-494e-9d28-6c1b6d154fae">

**Scenario 3**: even more explicit, and this seems off to me.
<img width="595" alt="Screenshot 2023-11-21 at 22 11 08" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/885c3fcd-bed4-4952-94d8-b8faeda5518c">

Were you able to distinguish between these scenarios? Should we? How?

Further, I want to know how to deal with missing time data. It is clear that if there is no time data on an utterance, an FTO for this utterance cannot be calculated. However, what if there is an utterance in the context window with missing time data? Should we therefore also not calculate an FTO?

Specifically:

**Scenario 4**: here, utterance B lacks time data, but is timed somewhere between A and C. A would be the obvious preceding utterance for C, so should the lack of time data for B matter at all?
![image](https://github.com/elpaco-escience/scikit-talk/assets/5747405/e63bb78e-bc0a-4203-944d-2d68a8e3af1c)

**Scenario 5**: now, B is timed similarly, but spoken by a different speaker. Here, it could be that C is in fact in response to B. However, it is possible that the real start time for B is within the planning window for C, and therefore B should be disregarded. We don't know this, however. Should we now abandon the FTO calculation for C?
<img width="429" alt="Screenshot 2023-11-21 at 22 47 46" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/82298f70-8377-4092-bae1-da475f631dc4">



Help appreciated!

**Comment by bvreede** [comment]
After checking the code and discussion shared on Basecamp, I came up with this:

<img width="873" alt="Screenshot 2023-11-30 at 11 53 20" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/eae02318-9ada-4b03-acfa-d8771bcdf415">

Essentially, this means that for an utterance to be relevant for FTO calculation, ANY utterances between utterance U (C in the scenarios above) and relevant utterance X (A in the scenarios above) must either have started less than the planning buffer before U, or they must fully overlap with X.

This means that in the scenarios above, only Scenario 1 leads to FTO calculation.

Comments welcome!

**Comment by mdingemanse** [comment]
Somehow I neglected to respond to this incredibly helpful flowchart back in Nov 2023. Sorry! 

so @bvreede, just to check, this is the current status, right? it will be very useful for documentation purposes
